
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class EncryptFrame extends javax.swing.JFrame {
    viscrypt vc = new viscrypt();
    
    /**
     * Creates new form NewJFrame
     */
    public EncryptFrame() {
        initComponents();
        jFrame1.setTitle("SHARES1");
        jFrame2.setTitle("SHARES2");
        setLocationRelativeTo(null);
        setTitle("Encrypt");
        setResizable(false);
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.PAGE_AXIS));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChoser = new javax.swing.JFileChooser();
        jFrame1 = new javax.swing.JFrame();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        scrollPane2 = new java.awt.ScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jFrame2 = new javax.swing.JFrame();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        scrollPane3 = new java.awt.ScrollPane();
        jLabel2 = new javax.swing.JLabel();
        fileChoser2 = new javax.swing.JFileChooser();
        namaCover1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        namaCover2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        namaSecret = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        fileChoser.setCurrentDirectory(new java.io.File("C:\\Users\\ACER\\Desktop\\SKRIPSI\\VISCRYPT\\image"));
        fileChoser.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);

        jFrame1.setLocation(new java.awt.Point(200, 100));
        jFrame1.setSize(new java.awt.Dimension(900, 700));

        jButton5.setText("Save");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");
        scrollPane2.add(jLabel1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jFrame2.setLocation(new java.awt.Point(900, 100));
        jFrame2.setSize(new java.awt.Dimension(900, 700));

        jButton6.setText("Save");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");
        scrollPane3.add(jLabel2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 463, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        fileChoser2.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        fileChoser2.setCurrentDirectory(new java.io.File("C:\\Users\\ACER\\Desktop\\SKRIPSI\\VISCRYPT\\image\\output"));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        namaCover1.setEditable(false);
        namaCover1.setBackground(new java.awt.Color(200, 200, 200));
        namaCover1.setText("tidak ada gambar yang dipilih");
        namaCover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaCover1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jButton1.setText("Pilih Cover 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        namaCover2.setEditable(false);
        namaCover2.setBackground(new java.awt.Color(200, 200, 200));
        namaCover2.setText("tidak ada gambar yang dipilih");
        namaCover2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaCover2ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jButton2.setText("Pilih Cover 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        namaSecret.setEditable(false);
        namaSecret.setBackground(new java.awt.Color(200, 200, 200));
        namaSecret.setText("tidak ada gambar yang dipilih");
        namaSecret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaSecretActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jButton3.setText("Pilih Secret");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jButton4.setText("GENERATE SHARES");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel3.setText("Silahkan Masukan Cover1, Cover2 dan Secret");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaSecret)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaCover2, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaCover1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaCover1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaCover2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaSecret, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    File imageCover1 = null;
    File imageCover2 = null;
    File imageSecret = null;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                    
        fileChoser.setFileFilter(new FileFilter() {
            public boolean accept(File arg0) {
                    if (arg0.isDirectory()) return true;
                    if (arg0.getName().toLowerCase().endsWith(".png")) return true;
                    if (arg0.getName().toLowerCase().endsWith(".jpg")) return true;
                    if (arg0.getName().toLowerCase().endsWith(".gif")) return true;
                    return false;
            }
            public String getDescription() {
                    return "Image";
            }
        });
        
        int ret = fileChoser.showOpenDialog(this);
        if (ret == fileChoser.APPROVE_OPTION) {
            imageCover1 = fileChoser.getSelectedFile();
            namaCover1.setText(imageCover1.getName());
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void namaCover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaCover1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaCover1ActionPerformed

    private void namaCover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaCover2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaCover2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        fileChoser.setFileFilter(new FileFilter() {
            public boolean accept(File arg0) {
                    if (arg0.isDirectory()) return true;
                    if (arg0.getName().toLowerCase().endsWith(".png")) return true;
                    if (arg0.getName().toLowerCase().endsWith(".jpg")) return true;
                    if (arg0.getName().toLowerCase().endsWith(".gif")) return true;
                    return false;
            }
            public String getDescription() {
                    return "Image";
            }
        });
        
        int ret = fileChoser.showOpenDialog(this);
        if (ret == fileChoser.APPROVE_OPTION) {
            imageCover2 = fileChoser.getSelectedFile();
            namaCover2.setText(imageCover2.getName());
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void namaSecretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaSecretActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaSecretActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        fileChoser.setFileFilter(new FileFilter() {
            public boolean accept(File arg0) {
                    if (arg0.isDirectory()) return true;
                    if (arg0.getName().toLowerCase().endsWith(".png")) return true;
                    if (arg0.getName().toLowerCase().endsWith(".jpg")) return true;
                    if (arg0.getName().toLowerCase().endsWith(".gif")) return true;
                    return false;
            }
            public String getDescription() {
                    return "Image";
            }
        });
        
        int ret = fileChoser.showOpenDialog(this);
        if (ret == fileChoser.APPROVE_OPTION) {
            imageSecret = fileChoser.getSelectedFile();
            namaSecret.setText(imageSecret.getName());
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    
    BufferedImage shares1;
    BufferedImage shares2;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(imageCover1 == null || !imageCover1.exists() || imageCover2 == null || !imageCover2.exists() || imageSecret == null || !imageSecret.exists()){
            JOptionPane.showMessageDialog(this, "File not found \nSilakan Pilih Gambar!", "ERROR", JOptionPane.ERROR_MESSAGE);      
            return;
        }else{
//      Mengecek kesamaan cover dan shares            
            if(imageCover1.getAbsolutePath()== imageSecret.getAbsolutePath()|| imageCover2.getAbsolutePath()== imageSecret.getAbsolutePath()){
                JOptionPane.showMessageDialog(this, "Gambar Cover dan Secret Tidak Boleh Sama!", "ERROR", JOptionPane.ERROR_MESSAGE);  
            }else{
        
        try {
          BufferedImage cover1 = ImageIO.read(imageCover1);
          BufferedImage cover2 = ImageIO.read(imageCover2);
          BufferedImage secret = ImageIO.read(imageSecret);
          
//        MENGECEK UKURAN GAMBAR
          if(vc.cekSize(cover1, cover2, secret)==false){
                JOptionPane.showMessageDialog(this, "Ukuran Gambar Berbda \nPastikan Memiilih Gambar Dengan Ukuran Yang Sama!", "ERROR", JOptionPane.ERROR_MESSAGE);
          }else{
              
//          MENGECEK RGB GAMBAR    
            if(vc.cekRGB(cover1)&vc.cekRGB(cover2)&vc.cekRGB(secret)){
                vc.generateShares(cover1, cover2, secret);
                shares1 = vc.getShares1();
                shares2 = vc.getShares2();

                jFrame1.setVisible(true);
                jFrame2.setVisible(true);
                jLabel1.setText("");
                jLabel2.setText("");
                jLabel1.setIcon(new ImageIcon(shares1));
                jLabel2.setIcon(new ImageIcon(shares2));
            }
            else{
                int dialog = JOptionPane.showConfirmDialog(this, "Salah Satu Image Mungkin Bukan Image Berwarna \nIngin Melanjutkan??", "Warning", JOptionPane.YES_NO_OPTION);
                if(dialog==0){
                vc.generateShares(cover1, cover2, secret);
                shares1 = vc.getShares1();
                shares2 = vc.getShares2();
                    
                    jFrame1.setVisible(true);
                    jFrame2.setVisible(true);
                    jLabel1.setText("");
                    jLabel2.setText("");
                    jLabel1.setIcon(new ImageIcon(shares1));
                    jLabel2.setIcon(new ImageIcon(shares2));
                }
            }
          }
        }catch (IOException ex) {
            System.out.println(ex);
        }
        }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        fileChoser2.setSelectedFile(new File("shares1.png"));
        fileChoser2.setDialogTitle("Save");
        if(fileChoser2.showSaveDialog(jPanel1)==JFileChooser.APPROVE_OPTION){
        File f = fileChoser2.getSelectedFile(); 
            if (!f.toString().endsWith(".png")) {
                f = new File(f.toString() + ".png");
            }
        try {
                ImageIO.write(shares1, "png", f);
        } catch (IOException e1) {
                JOptionPane.showMessageDialog(this, "Could not Save file because: " + e1.getLocalizedMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        fileChoser2.setSelectedFile(new File("shares2.png"));
        fileChoser2.setDialogTitle("Save");
        if(fileChoser2.showSaveDialog(jPanel2)==JFileChooser.APPROVE_OPTION){
        File f = fileChoser2.getSelectedFile(); 
            if (!f.toString().endsWith(".png")) {
                f = new File(f.toString() + ".png");
            }
        try {
                ImageIO.write(shares2, "png", f);
        } catch (IOException e1) {
                JOptionPane.showMessageDialog(this, "Could not Save file because: " + e1.getLocalizedMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncryptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncryptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncryptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncryptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EncryptFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChoser;
    private javax.swing.JFileChooser fileChoser2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField namaCover1;
    private javax.swing.JTextField namaCover2;
    private javax.swing.JTextField namaSecret;
    private java.awt.ScrollPane scrollPane2;
    private java.awt.ScrollPane scrollPane3;
    // End of variables declaration//GEN-END:variables
}
